### PR TITLE
Ruby 1.8 compatability

### PR DESCRIPTION
**Pull request by mikz**
Hi!

I found issue when using Ruby 1.8 -

`File.new Tempfile.new("bla")` raises `can't convert Tempfile into String` exception

calling `#path` on tempfile ensures that `File.new` is called with String.

Tmp.fs should always return Tempfile right?

### CODE REVIEW

**Comment by exviva** [comment]
Thanks @mikz. I've enabled 1.8.7 on Travis, and it won't even start the build (due to using 1.9 hash syntax): http://travis-ci.org/#!/exviva/paperclip-storage-tmp/jobs/1622507.

If you can get the build to run on 1.8.7, **and** fail, **and** your fix will make it pass, then I'll gladly merge it in.

**Comment by mikz** [comment]
@exviva done & green http://travis-ci.org/#!/mikz/paperclip-storage-tmp

**Comment by exviva** [comment]
One last thing: please add a changelog entry. Then I'll merge. Thanks!

**Comment by mikz** [comment]
@exviva done. Thanks for cooperation!

**Comment by exviva** [comment]
Oh man...sorry I'm being so pedantic, but could you put the changelog entry on the very top and squash your commits? :)

**Comment by mikz** [comment]
No problem :)

**Comment by mikz** [comment]
Like this? @exviva

**Comment by exviva** [comment]
Perfect! Thanks

**Comment by exviva** [comment]
I've released it as 0.0.4.

**Comment by mikz** [comment]
Thank you very much!

**Pull request merged**
